@startuml
title 画面遷移図
(*)--> "ログイン画面"
--> "メニュー画面\n「自分の記録」\n「他の人の記録」"
if "" then
    --> [自分の記録]"「聖遺物・武器」\n「セット」"
    if "" then
        --> [聖遺物・武器]"参照及び編集画面"
    else
        --> [セット]"セットの参照及び編集画面"
    endif
else
    --> [他の人の記録]"「聖遺物検索」\n「セット検索」"
    if "" then
        --> [聖遺物検索]"検索条件入力画面"
        --> "検索結果画面"
    else
        --> [セット検索]"セット検索画面"
        --> "検索結果画面"
    endif
endif
@enduml